export default function PrivacyPolicyPage() {
  return (
    <div className="w-full max-w-4xl mx-auto py-12 px-[15px] text-gray-900 dark:text-gray-100 leading-relaxed">
      <h1 className="text-3xl md:text-4xl font-extrabold mb-2">Privacy Policy</h1>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-8 border-b border-gray-200 dark:border-gray-800 pb-4">
        Last updated: August 2026
      </p>

      <div className="space-y-8">
        <section>
          <p className="mb-4">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-joint-green">Interpretation and Definitions</h2>
          <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
          <p className="mb-4">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          
          <h3 className="text-xl font-semibold mb-4">Definitions</h3>
          <ul className="list-disc pl-6 space-y-3 text-gray-700 dark:text-gray-300">
            <li><strong>Account</strong> means a unique account created for You to access Our Service or parts of Our Service.</li>
            <li><strong>Application / Website</strong> refers to GameJoint, accessible from <a href="https://game-joint.net" className="text-joint-green hover:underline">https://game-joint.net</a>.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to GameJoint.</li>
            <li><strong>Cookies / Local Storage</strong> refer to small files or data tokens placed on Your device to maintain session state and preferences.</li>
            <li><strong>Country/State</strong> refers to: Turkey.</li>
            <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company, including third-party security services like Cloudflare.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-joint-green">Collecting and Using Your Personal Information</h2>
          
          <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
          <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
          <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This includes:</p>
          <ul className="list-disc pl-6 space-y-1 text-gray-700 dark:text-gray-300 mb-4">
            <li>Email address</li>
            <li>Username</li>
            <li>Date of Birth</li>
          </ul>

          <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data & Security</h4>
          <p className="mb-4">
            Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (IP address), browser type, and browser version. 
            We explicitly process your IP address for security purposes, including validating requests through our security provider (Cloudflare Turnstile) to prevent automated bot attacks, and for sending you email alerts if a login occurs from a new location.
          </p>

          <h4 className="text-lg font-semibold mt-4 mb-2">Authentication and Local Storage</h4>
          <p className="mb-4">
            Instead of traditional tracking cookies, Our Service primarily utilizes JSON Web Tokens (JWT) stored in your browser's Local Storage. This is strictly a "Necessary/Essential" mechanism required to keep you logged into your Account securely. If you clear your browser's local storage, you will be logged out of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-joint-green">Use of Your Personal Data</h2>
          <ul className="list-disc pl-6 space-y-3 text-gray-700 dark:text-gray-300 mb-6">
            <li><strong>To provide and maintain Our Service:</strong> Including monitoring the usage and security of Our Service.</li>
            <li><strong>To manage Your Account:</strong> To manage Your registration as a user of the Service.</li>
            <li><strong>To contact You:</strong> Regarding account security alerts (e.g., new login locations), password resets, and mandatory email verification.</li>
          </ul>
          
          <p className="font-semibold mb-2">We may share Your Personal Data in the following situations:</p>
          <ul className="list-disc pl-6 space-y-3 text-gray-700 dark:text-gray-300">
            <li><strong>With Service Providers:</strong> Such as Cloudflare to secure our endpoints, or our email delivery provider for transactional emails.</li>
            <li><strong>With other users:</strong> When You share reviews, ratings (JointScores), or interact in public areas, Your username and generated content may be viewed by all users.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-joint-green">Retention and Deletion</h2>
          <p className="mb-4">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. 
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account settings.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-joint-green">Children's Privacy</h2>
          <p className="mb-4">
            The Service is not directed to, and We do not knowingly collect Personal Information from, anyone under the age of 16. If We become aware that We have collected Personal Information from anyone under the age of 16, We will take steps to remove that information from Our servers.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4 text-joint-green">Contact Us</h2>
          <p>If You have any questions about this Privacy Policy, You can contact Us:</p>
          <ul className="list-disc pl-6 mt-2 text-gray-700 dark:text-gray-300">
            <li>By email: <a href="mailto:gamejoint.noreply@gmail.com" className="text-joint-green hover:underline">gamejoint.noreply@gmail.com</a></li>
          </ul>
        </section>
      </div>
    </div>
  );
}